package main

import (
	"github.com/rur/treetop"
	"github.com/rur/treetop-demo/page"

	"github.com/rur/treetop-demo/page/inline"
	"github.com/rur/treetop-demo/page/intro"
)

// Code generated by go generate; DO NOT EDIT.

func registerPages(hlp page.Helper, exec treetop.ViewExecutor) {
	// register pages
	inline.Routes(hlp, exec)
	intro.Routes(hlp, exec)
}
